import type { ExplorerFile, Tag, TagClass } from '@/types/explorer'

export const tagClasses: TagClass[] = [
    {
        id: 1,
        name: 'General',
    },
    {
        id: 2,
        name: 'Customers',
    },
    {
        id: 3,
        name: 'Sale quotations',
    },
    {
        id: 4,
        name: 'Employee contract',
    },
    {
        id: 5,
        name: 'SEA region',
    },
    {
        id: 6,
        name: 'Brand guideline',
    },
    {
        id: 7,
        name: 'Gift for partner 2025',
    },
    {
        id: 8,
        name: 'Marketing plan',
    },
    {
        id: 9,
        name: 'Pitch presentation',
    },
    {
        id: 10,
        name: 'Expo',
    },
    {
        id: 11,
        name: 'User guide',
    },
    {
        id: 12,
        name: 'Employee handbook',
    },
    {
        id: 13,
        name: 'Financial statement',
    },
    {
        id: 14,
        name: 'Requirement',
    },
    {
        id: 15,
        name: 'Clients',
    },
    {
        id: 16,
        name: 'Logistic',
    },
    {
        id: 17,
        name: 'Vendors',
    },
    {
        id: 18,
        name: 'Manufacturer',
    },
    {
        id: 19,
        name: 'Factory',
    },
    {
        id: 20,
        name: 'Market research',
    },
    {
        id: 21,
        name: 'Competitor analyst',
    },
    {
        id: 22,
        name: 'Annual report',
    },
    {
        id: 23,
        name: 'Bonus for employee',
    },
    {
        id: 24,
        name: 'Annual revenue',
    },
    {
        id: 25,
        name: 'Helpful',
    },
    {
        id: 26,
        name: 'Employee image',
    },
    {
        id: 27,
        name: 'Company trip',
    },
    {
        id: 28,
        name: 'Career path for employee',
    },
    {
        id: 29,
        name: 'Warehouse contract',
    },
    {
        id: 30,
        name: 'Company equipment',
    },
    {
        id: 31,
        name: 'Business plan new technology',
    },
]

export const tags: Tag[] = [
    {
        id: 1,
        tagClassId: 1,
        name: 'Document',
    },
    {
        id: 2,
        tagClassId: 2,
        name: 'Customer List',
    },
    {
        id: 3,
        tagClassId: 3,
        name: 'Quotation 2023',
    },
    {
        id: 4,
        tagClassId: 4,
        name: 'Contract 2023',
    },
    {
        id: 5,
        tagClassId: 5,
        name: 'SEA Market Analysis',
    },
    {
        id: 6,
        tagClassId: 6,
        name: 'Brand Colors',
    },
    {
        id: 7,
        tagClassId: 7,
        name: 'Partner Gifts',
    },
    {
        id: 8,
        tagClassId: 8,
        name: 'Marketing Q1',
    },
    {
        id: 9,
        tagClassId: 9,
        name: 'Pitch Deck',
    },
    {
        id: 10,
        tagClassId: 10,
        name: 'Expo 2023',
    },
    {
        id: 11,
        tagClassId: 11,
        name: 'User Manual',
    },
    {
        id: 12,
        tagClassId: 12,
        name: 'Handbook 2023',
    },
    {
        id: 13,
        tagClassId: 13,
        name: 'Q1 Financials',
    },
    {
        id: 14,
        tagClassId: 14,
        name: 'Project Requirements',
    },
    {
        id: 15,
        tagClassId: 15,
        name: 'Client List',
    },
    {
        id: 16,
        tagClassId: 16,
        name: 'Logistics Plan',
    },
    {
        id: 17,
        tagClassId: 17,
        name: 'Vendor Contracts',
    },
    {
        id: 18,
        tagClassId: 18,
        name: 'Manufacturing Plan',
    },
    {
        id: 19,
        tagClassId: 19,
        name: 'Factory Layout',
    },
    {
        id: 20,
        tagClassId: 20,
        name: 'Market Research 2023',
    },
    {
        id: 21,
        tagClassId: 21,
        name: 'Competitor Analysis',
    },
    {
        id: 22,
        tagClassId: 22,
        name: 'Annual Report 2022',
    },
    {
        id: 23,
        tagClassId: 23,
        name: 'Employee Bonuses',
    },
    {
        id: 24,
        tagClassId: 24,
        name: 'Revenue 2022',
    },
    {
        id: 25,
        tagClassId: 25,
        name: 'Helpful Tips',
    },
    {
        id: 26,
        tagClassId: 26,
        name: 'Employee Photos',
    },
    {
        id: 27,
        tagClassId: 27,
        name: 'Company Trip 2023',
    },
    {
        id: 28,
        tagClassId: 28,
        name: 'Career Path',
    },
    {
        id: 29,
        tagClassId: 29,
        name: 'Warehouse Lease',
    },
    {
        id: 30,
        tagClassId: 30,
        name: 'Equipment List',
    },
    {
        id: 31,
        tagClassId: 31,
        name: 'Tech Business Plan',
    },
    {
        id: 32,
        tagClassId: 1,
        name: 'General Info',
    },
    {
        id: 33,
        tagClassId: 2,
        name: 'Customer Feedback',
    },
    {
        id: 34,
        tagClassId: 3,
        name: 'Sales Data',
    },
    {
        id: 35,
        tagClassId: 4,
        name: 'Employee Contracts',
    },
    {
        id: 36,
        tagClassId: 5,
        name: 'SEA Trends',
    },
    {
        id: 37,
        tagClassId: 6,
        name: 'Brand Assets',
    },
    {
        id: 38,
        tagClassId: 7,
        name: 'Partner Relations',
    },
    {
        id: 39,
        tagClassId: 8,
        name: 'Marketing Strategy',
    },
    {
        id: 40,
        tagClassId: 9,
        name: 'Presentation Slides',
    },
    {
        id: 41,
        tagClassId: 10,
        name: 'Expo Booth',
    },
    {
        id: 42,
        tagClassId: 11,
        name: 'User Instructions',
    },
    {
        id: 43,
        tagClassId: 12,
        name: 'Employee Guide',
    },
    {
        id: 44,
        tagClassId: 13,
        name: 'Financial Overview',
    },
    {
        id: 45,
        tagClassId: 14,
        name: 'Project Specs',
    },
    {
        id: 46,
        tagClassId: 15,
        name: 'Client Contracts',
    },
    {
        id: 47,
        tagClassId: 16,
        name: 'Logistics Schedule',
    },
    {
        id: 48,
        tagClassId: 17,
        name: 'Vendor Agreements',
    },
    {
        id: 49,
        tagClassId: 18,
        name: 'Manufacturing Schedule',
    },
    {
        id: 50,
        tagClassId: 19,
        name: 'Factory Operations',
    },
    {
        id: 51,
        tagClassId: 20,
        name: 'Market Insights',
    },
    {
        id: 52,
        tagClassId: 21,
        name: 'Competitor Report',
    },
    {
        id: 53,
        tagClassId: 22,
        name: 'Annual Summary',
    },
    {
        id: 54,
        tagClassId: 23,
        name: 'Employee Rewards',
    },
    {
        id: 55,
        tagClassId: 24,
        name: 'Revenue Breakdown',
    },
    {
        id: 56,
        tagClassId: 25,
        name: 'Helpful Resources',
    },
    {
        id: 57,
        tagClassId: 26,
        name: 'Staff Photos',
    },
    {
        id: 58,
        tagClassId: 27,
        name: 'Company Outing',
    },
    {
        id: 59,
        tagClassId: 28,
        name: 'Career Development',
    },
    {
        id: 60,
        tagClassId: 29,
        name: 'Warehouse Agreement',
    },
    {
        id: 61,
        tagClassId: 30,
        name: 'Equipment Inventory',
    },
    {
        id: 62,
        tagClassId: 31,
        name: 'Tech Plan',
    },
]

export const files: ExplorerFile[] = [
    {
        id: 1,
        name: 'Document 1',
        tags: [1, 2, 3],
        type: 'png',
        owner: 'John Doe',
        size: 12.34,
    },
    {
        id: 2,
        name: 'Customer List',
        tags: [2, 15, 33],
        type: 'pdf',
        owner: 'Jane Smith',
        size: 23.45,
    },
    {
        id: 3,
        name: 'Sales Quotation',
        tags: [3, 34, 4],
        type: 'jpg',
        owner: 'Alice Johnson',
        size: 34.56,
    },
    {
        id: 4,
        name: 'Employee Contract',
        tags: [4, 35, 2],
        type: 'png',
        owner: 'Bob Brown',
        size: 45.67,
    },
    {
        id: 5,
        name: 'SEA Market Analysis',
        tags: [5, 36],
        type: 'png',
        owner: 'Charlie Davis',
        size: 11.22,
    },
    {
        id: 6,
        name: 'Brand Guidelines',
        tags: [6, 37, 8],
        type: 'png',
        owner: 'Diana Evans',
        size: 22.33,
    },
    {
        id: 7,
        name: 'Partner Gifts',
        tags: [7, 38, 2],
        type: 'png',
        owner: 'Ethan Harris',
        size: 33.44,
    },
    {
        id: 8,
        name: 'Marketing Plan',
        tags: [8, 39, 3],
        type: 'pdf',
        owner: 'Fiona Clark',
        size: 44.55,
    },
    {
        id: 9,
        name: 'Pitch Presentation',
        tags: [9, 40, 34],
        type: 'pdf',
        owner: 'George Lewis',
        size: 12.34,
    },
    {
        id: 10,
        name: 'Expo Booth',
        tags: [10, 41, 20],
        type: 'jpg',
        owner: 'Hannah Walker',
        size: 23.45,
    },
    {
        id: 11,
        name: 'User Guide',
        tags: [11, 42, 24],
        type: 'pdf',
        owner: 'Ian Young',
        size: 34.56,
    },
    {
        id: 12,
        name: 'Employee Handbook',
        tags: [12, 43, 15],
        type: 'pdf',
        owner: 'Jack King',
        size: 45.67,
    },
    {
        id: 13,
        name: 'Financial Statement',
        tags: [13, 44, 28],
        type: 'png',
        owner: 'Karen Wright',
        size: 11.22,
    },
    {
        id: 14,
        name: 'Requirement Document',
        tags: [14, 45, 25],
        type: 'jpg',
        owner: 'Liam Scott',
        size: 22.33,
    },
    {
        id: 15,
        name: 'Client List',
        tags: [15, 46, 4],
        type: 'png',
        owner: 'Mia Green',
        size: 33.44,
    },
    {
        id: 16,
        name: 'Logistics Plan',
        tags: [16, 47, 5],
        type: 'jpg',
        owner: 'Noah Adams',
        size: 44.55,
    },
    {
        id: 17,
        name: 'Vendor Contracts',
        tags: [17, 48, 22],
        type: 'pdf',
        owner: 'Olivia Baker',
        size: 12.34,
    },
    {
        id: 18,
        name: 'Manufacturing Plan',
        tags: [18, 49, 33],
        type: 'pdf',
        owner: 'Paul Carter',
        size: 23.45,
    },
    {
        id: 19,
        name: 'Factory Layout',
        tags: [19, 50, 20],
        type: 'jpg',
        owner: 'Quinn Mitchell',
        size: 34.56,
    },
    {
        id: 20,
        name: 'Market Research',
        tags: [20, 51],
        type: 'pdf',
        owner: 'Rachel Perez',
        size: 45.67,
    },
    {
        id: 21,
        name: 'Competitor Analysis',
        tags: [21, 52, 44],
        type: 'jpg',
        owner: 'Sam Roberts',
        size: 11.22,
    },
    {
        id: 22,
        name: 'Annual Report',
        tags: [22, 53, 31],
        type: 'png',
        owner: 'Tina Turner',
        size: 22.33,
    },
    {
        id: 23,
        name: 'Employee Bonuses',
        tags: [23, 54, 12],
        type: 'png',
        owner: 'Uma Thompson',
        size: 33.44,
    },
    {
        id: 24,
        name: 'Annual Revenue',
        tags: [24, 55, 10],
        type: 'png',
        owner: 'Victor White',
        size: 44.55,
    },
    {
        id: 25,
        name: 'Helpful Tips',
        tags: [25, 56, 11],
        type: 'png',
        owner: 'Wendy Hall',
        size: 12.34,
    },
    {
        id: 26,
        name: 'Employee Image',
        tags: [26, 57, 35],
        type: 'jpg',
        owner: 'Xander Allen',
        size: 23.45,
    },
    {
        id: 27,
        name: 'Company Trip',
        tags: [27, 58, 9],
        type: 'jpg',
        owner: 'Yara Nelson',
        size: 34.56,
    },
    {
        id: 28,
        name: 'Career Path',
        tags: [28, 59, 2],
        type: 'pdf',
        owner: 'Zachary Hill',
        size: 45.67,
    },
    {
        id: 29,
        name: 'Warehouse Contract',
        tags: [29, 60, 44],
        type: 'png',
        owner: 'Aaron Lee',
        size: 11.22,
    },
    {
        id: 30,
        name: 'Company Equipment',
        tags: [30, 61, 5],
        type: 'pdf',
        owner: 'Bella Kim',
        size: 22.33,
    },
    {
        id: 31,
        name: 'Business Plan',
        tags: [31, 62, 17],
        type: 'jpg',
        owner: 'Chris Moore',
        size: 33.44,
    },
    {
        id: 32,
        name: 'General Info',
        tags: [1, 32, 18],
        type: 'pdf',
        owner: 'Dana Clark',
        size: 44.55,
    },
    {
        id: 33,
        name: 'Customer Feedback',
        tags: [2, 33, 19],
        type: 'pdf',
        owner: 'Eli Martinez',
        size: 12.34,
    },
    {
        id: 34,
        name: 'Sales Data',
        tags: [3, 34, 55],
        type: 'pdf',
        owner: 'Faye Anderson',
        size: 23.45,
    },
    {
        id: 35,
        name: 'Employee Contracts',
        tags: [4, 35, 26],
        type: 'png',
        owner: 'Gabe Thomas',
        size: 34.56,
    },
    {
        id: 36,
        name: 'SEA Trends',
        tags: [5, 36, 32],
        type: 'pdf',
        owner: 'Holly Jackson',
        size: 45.67,
    },
    {
        id: 37,
        name: 'Brand Assets',
        tags: [6, 37, 14],
        type: 'pdf',
        owner: 'Ian Harris',
        size: 11.22,
    },
    {
        id: 38,
        name: 'Partner Relations',
        tags: [7, 38, 52],
        type: 'pdf',
        owner: 'Jill Martinez',
        size: 22.33,
    },
    {
        id: 39,
        name: 'Marketing Strategy',
        tags: [8, 39, 58],
        type: 'png',
        owner: 'Kyle Robinson',
        size: 33.44,
    },
    {
        id: 40,
        name: 'Presentation Slides',
        tags: [9, 40, 37],
        type: 'jpg',
        owner: 'Lara Scott',
        size: 44.55,
    },
    {
        id: 41,
        name: 'Expo 2023',
        tags: [10, 41, 22],
        type: 'jpg',
        owner: 'Mona Lisa',
        size: 12.34,
    },
    {
        id: 42,
        name: 'User Manual',
        tags: [11, 42, 23],
        type: 'pdf',
        owner: 'Nina Brown',
        size: 23.45,
    },
    {
        id: 43,
        name: 'Handbook 2023',
        tags: [12, 43, 24],
        type: 'pdf',
        owner: 'Oscar Green',
        size: 34.56,
    },
    {
        id: 44,
        name: 'Q1 Financials',
        tags: [13, 44, 25],
        type: 'png',
        owner: 'Paul White',
        size: 45.67,
    },
    {
        id: 45,
        name: 'Project Requirements',
        tags: [14, 45, 26],
        type: 'jpg',
        owner: 'Quincy Black',
        size: 11.22,
    },
    {
        id: 46,
        name: 'Client List',
        tags: [15, 46, 27],
        type: 'png',
        owner: 'Rachel Blue',
        size: 22.33,
    },
    {
        id: 47,
        name: 'Logistics Plan',
        tags: [16, 47, 28],
        type: 'jpg',
        owner: 'Sam Yellow',
        size: 33.44,
    },
    {
        id: 48,
        name: 'Vendor Contracts',
        tags: [17, 48, 29],
        type: 'pdf',
        owner: 'Tina Red',
        size: 44.55,
    },
    {
        id: 49,
        name: 'Manufacturing Plan',
        tags: [18, 49, 30],
        type: 'pdf',
        owner: 'Uma Purple',
        size: 12.34,
    },
    {
        id: 50,
        name: 'Factory Layout',
        tags: [19, 50, 31],
        type: 'jpg',
        owner: 'Victor Orange',
        size: 23.45,
    },
    {
        id: 51,
        name: 'Market Research 2023',
        tags: [20, 51, 32],
        type: 'jpg',
        owner: 'Wendy Pink',
        size: 34.56,
    },
    {
        id: 52,
        name: 'Competitor Analysis',
        tags: [21, 52, 33],
        type: 'jpg',
        owner: 'Xander Gray',
        size: 45.67,
    },
    {
        id: 53,
        name: 'Annual Report 2022',
        tags: [22, 53, 34],
        type: 'png',
        owner: 'Yara Cyan',
        size: 11.22,
    },
    {
        id: 54,
        name: 'Employee Bonuses',
        tags: [23, 54, 35],
        type: 'jpg',
        owner: 'Zachary Magenta',
        size: 22.33,
    },
    {
        id: 55,
        name: 'Revenue 2022',
        tags: [24, 55, 36],
        type: 'jpg',
        owner: 'Aaron Indigo',
        size: 33.44,
    },
    {
        id: 56,
        name: 'Helpful Tips',
        tags: [25, 56, 37],
        type: 'pdf',
        owner: 'Bella Violet',
        size: 44.55,
    },
    {
        id: 57,
        name: 'Employee Photos',
        tags: [26, 57, 38],
        type: 'jpg',
        owner: 'Chris Brown',
        size: 12.34,
    },
    {
        id: 58,
        name: 'Company Trip 2023',
        tags: [27, 58, 39],
        type: 'jpg',
        owner: 'Dana Green',
        size: 23.45,
    },
    {
        id: 59,
        name: 'Career Development',
        tags: [28, 59, 40],
        type: 'pdf',
        owner: 'Eli Blue',
        size: 34.56,
    },
    {
        id: 60,
        name: 'Warehouse Agreement',
        tags: [29, 60, 41],
        type: 'png',
        owner: 'Faye Red',
        size: 45.67,
    },
    {
        id: 61,
        name: 'Equipment Inventory',
        tags: [30, 61, 42],
        type: 'pdf',
        owner: 'Gabe Yellow',
        size: 11.22,
    },
    {
        id: 62,
        name: 'Tech Plan',
        tags: [31, 62, 43],
        type: 'jpg',
        owner: 'Holly Purple',
        size: 22.33,
    },
    {
        id: 63,
        name: 'General Document',
        tags: [1, 32, 44],
        type: 'jpg',
        owner: 'Ian Orange',
        size: 33.44,
    },
    {
        id: 64,
        name: 'Customer Insights',
        tags: [2, 33, 45],
        type: 'jpg',
        owner: 'Jill Pink',
        size: 44.55,
    },
    {
        id: 65,
        name: 'Sales Report',
        tags: [3, 34, 46],
        type: 'png',
        owner: 'Kyle Gray',
        size: 12.34,
    },
    {
        id: 66,
        name: 'Employee Records',
        tags: [4, 35, 47],
        type: 'png',
        owner: 'Lara Cyan',
        size: 23.45,
    },
    {
        id: 67,
        name: 'Market Trends',
        tags: [5, 36, 48],
        type: 'pdf',
        owner: 'Mona Magenta',
        size: 34.56,
    },
    {
        id: 68,
        name: 'Brand Guidelines 2023',
        tags: [6, 37, 49],
        type: 'pdf',
        owner: 'Nina Indigo',
        size: 45.67,
    },
    {
        id: 69,
        name: 'Partner Gifts 2023',
        tags: [7, 38, 50],
        type: 'jpg',
        owner: 'Oscar Blue',
        size: 11.22,
    },
    {
        id: 70,
        name: 'Marketing Plan Q2',
        tags: [8, 39, 51],
        type: 'pdf',
        owner: 'Paul Green',
        size: 22.33,
    },
    {
        id: 71,
        name: 'Pitch Deck 2023',
        tags: [9, 40, 52],
        type: 'pdf',
        owner: 'Quincy Red',
        size: 33.44,
    },
    {
        id: 72,
        name: 'Expo 2024',
        tags: [10, 41, 53],
        type: 'jpg',
        owner: 'Rachel Yellow',
        size: 44.55,
    },
    {
        id: 73,
        name: 'User Instructions 2023',
        tags: [11, 42, 54],
        type: 'pdf',
        owner: 'Sam Purple',
        size: 12.34,
    },
    {
        id: 74,
        name: 'Employee Guide 2023',
        tags: [12, 43, 55],
        type: 'pdf',
        owner: 'Tina Orange',
        size: 23.45,
    },
    {
        id: 75,
        name: 'Financial Overview Q2',
        tags: [13, 44, 56],
        type: 'png',
        owner: 'Uma Pink',
        size: 34.56,
    },
    {
        id: 76,
        name: 'Project Specs 2023',
        tags: [14, 45, 57],
        type: 'jpg',
        owner: 'Victor Gray',
        size: 45.67,
    },
    {
        id: 77,
        name: 'Client Contracts 2023',
        tags: [15, 46, 58],
        type: 'png',
        owner: 'Wendy Cyan',
        size: 11.22,
    },
    {
        id: 78,
        name: 'Logistics Schedule Q2',
        tags: [16, 47, 59],
        type: 'jpg',
        owner: 'Xander Magenta',
        size: 22.33,
    },
    {
        id: 79,
        name: 'Vendor Agreements 2023',
        tags: [17, 48, 60],
        type: 'pdf',
        owner: 'Yara Indigo',
        size: 33.44,
    },
    {
        id: 80,
        name: 'Manufacturing Schedule Q2',
        tags: [18, 49, 61],
        type: 'pdf',
        owner: 'Zachary Violet',
        size: 44.55,
    },
    {
        id: 81,
        name: 'Factory Operations 2023',
        tags: [19, 50, 62],
        type: 'jpg',
        owner: 'Aaron Brown',
        size: 12.34,
    },
    {
        id: 82,
        name: 'Market Insights Q2',
        tags: [20, 51, 1],
        type: 'jpg',
        owner: 'Bella Green',
        size: 23.45,
    },
    {
        id: 83,
        name: 'Competitor Report Q2',
        tags: [21, 52, 2],
        type: 'jpg',
        owner: 'Chris Blue',
        size: 34.56,
    },
    {
        id: 84,
        name: 'Annual Summary 2023',
        tags: [22, 53, 3],
        type: 'png',
        owner: 'Dana Red',
        size: 45.67,
    },
    {
        id: 85,
        name: 'Employee Rewards Q2',
        tags: [23, 54, 4],
        type: 'jpg',
        owner: 'Eli Yellow',
        size: 11.22,
    },
    {
        id: 86,
        name: 'Revenue Breakdown Q2',
        tags: [24, 55, 5],
        type: 'jpg',
        owner: 'Faye Purple',
        size: 22.33,
    },
    {
        id: 87,
        name: 'Helpful Resources Q2',
        tags: [25, 56, 6],
        type: 'pdf',
        owner: 'Gabe Orange',
        size: 33.44,
    },
    {
        id: 88,
        name: 'Staff Photos Q2',
        tags: [26, 57, 7],
        type: 'jpg',
        owner: 'Holly Pink',
        size: 44.55,
    },
]
